### ISSUE TITLE
ModuleNotFoundError: No module named 'captchaaccounts'

### ISSUE THREAD

**Issue by encompass** [praekelt/django-recaptcha#148]
I was attempting to setup this feature into my application but got the following:

> 
> (ENV) encompass@gladys:~/Projects/industryhack$ ./industryhack/manage.py 
> /home/encompass/Projects/industryhack/ENV/lib/python3.6/site-packages/dotenv.py:56: UserWarning: Not reading .env - it doesn't exist.
>   warnings.warn("Not reading {0} - it doesn't exist.".format(dotenv))
> using CONSOLE backend for Email
> Traceback (most recent call last):
>   File "./industryhack/manage.py", line 16, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/encompass/Projects/industryhack/ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/home/encompass/Projects/industryhack/ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
>     django.setup()
>   File "/home/encompass/Projects/industryhack/ENV/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/encompass/Projects/industryhack/ENV/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/home/encompass/Projects/industryhack/ENV/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
>     module = import_module(entry)
>   File "/home/encompass/Projects/industryhack/ENV/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'captchaaccounts'
> 

I was following the tutorial on how to install it.
I can import captcha and it seems to be installed, but can't startup django with it in INSTALLED_APPS.

Django 1.11.5
Python 3.6.3

**Comment by phala** [comment]
hi @encompass. Please verify that `settings.INSTALLED_APPS` is a comma separated list
