### ISSUE TITLE
NotImplementedError: subclasses of Widget must provide a render() method

### ISSUE THREAD

**Issue by amcorreia** [praekelt/django-recaptcha#154]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django_performance_testing/utils.py", line 51, in context_manager_wrapper
    return fn(*a, **kw)
  File "/app/demo/tests/test_views.py", line 161, in test_user_form_pass_to_context
    response = self.do_get()
  File "/app/demo/tests/test_views.py", line 152, in do_get
    return self.client.get(reverse('demo:start'))
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 529, in get
    **extra)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 333, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/usr/local/lib/python2.7/site-packages/django_performance_testing/test_client.py", line 15, in client_request_that_fails_for_too_many_queries
    return orig_client_request(client_self, **request)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/app/demo/views.py", line 123, in start
    return render(request, template_name, context)
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/site-packages/django_performance_testing/templates.py", line 23, in template_render_that_fails_for_too_many_queries
    return orig_template_render(template_self, *a, **kw)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1050, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1028, in render_value_in_context
    value = force_text(value)
  File "/usr/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/usr/local/lib/python2.7/site-packages/django/utils/html.py", line 382, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/usr/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "/usr/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/usr/local/lib/python2.7/site-packages/django/forms/widgets.py", line 224, in render
    raise NotImplementedError('subclasses of Widget must provide a render() method')
NotImplementedError: subclasses of Widget must provide a render() method

If I comment in forms.py the line
```
        captcha = ReCaptchaField()
```

the error message is gone. This code was working without any errors before.
I'm using:
Python 2.7
Django 1.10.8
Django-recaptcha 1.4.0

**Comment by phala** [comment]
@amcorreia support for Django 1.10 was dropped in 1.4.0.
Use 1.3.1

**Comment by amcorreia** [comment]
@phala using 1.3.1 I have the error "reCAPTCHA v1 IS SHUTDOWN"

**Comment by jowolf** [comment]
I am getting this exact error as well, but I am on Django 1.11.13 (with django-recaptcha 1.4.0)

**Comment by scyhhe** [comment]
> @amcorreia support for Django 1.10 was dropped in 1.4.0.
> Use 1.3.1

Just saved my life right there... was busting my head the whole day. Thanks!
