### ISSUE TITLE
No module named captcha

### ISSUE THREAD

**Issue by lbazan** [praekelt/django-recaptcha#41]
$ python -m unittest tests.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "tests.py", line 4, in <module>
    from captcha import fields
ImportError: No module named captcha

**Comment by AltusBarry** [comment]
As this is a django app you need to test it using _python manage.py test captcha_. 
Alternatively if you are testing the app repo you should use _python setup.py test_.

At present there is an issue if you have _NOCAPTCHA = True_ in your settings.py it will fail, due to a domain site key issue with the newer version of reCAPTCHA and it not working on dev or test instances

Naturally if the tests keep failing please feel free to re-open the ticket with any new information
